### ISSUE TITLE
add documentation for usage

### ISSUE THREAD

**Issue by mateodelnorte** [scorpwarp23/ip-blocker#1]
Hi, 

I'm having trouble understanding how to use your package. I see the configuration usage, but don't understand how exactly to add whitelist or blacklist ips or ranges. 

Thx.

Matt

**Comment by scorpwarp23** [comment]
HI Matt,

The documentation has been provided already as per the README

**To Push an IP Address to the Hashmap**

To add an IP address to the hashmap simply call `YOUR_APP_URL/"PUSH_IP_ROUTE"?secret_key="YOUR_SECRET_KEY"&ip_address="THE_IP_ADDRESS"` as a **GET** request. It will return **1** if successful or **0** for failure.

e.g. `http://localhost:3000/push_ip?secret_key=SJ4tk6nv35WS8b6PT3K799K86d549m535Sfm8gHY6y6zAm97928896283S568n5S&ip_address=192.168.0.100`


**To Pull an IP Address from the Hashmap**

To remove an IP address to the hashmap simply call `YOUR_APP_URL/"PULL_IP_ROUTE"?secret_key="YOUR_SECRET_KEY"&ip_address="THE_IP_ADDRESS"` as a **GET** request. It will return **1** if successful or **0** for failure.

e.g. `http://localhost:3000/pull_ip?secret_key=SJ4tk6nv35WS8b6PT3K799K86d549m535Sfm8gHY6y6zAm97928896283S568n5S&ip_address=192.168.0.100`


So all you need to do is make an HTTP Request for the same. You can do this via CURL or simply via opening a browser tab and opening the above URLs The reason for doing it this way is so that IP Addresses can be added to the whitelist/blacklist on a live system without having to shutdown. 

Additionally the mode of operation for blacklist/whitelist is via a config variable.

In your main Server Block set it as follows:

```IP_BLOCKER.default_rule="blacklist" ``` for blacklisting as the mode of operation - any IP addresses you then add will be blocked and rerouted to the `IP_BLOCKER.redirect_url` provided. 

OR 

```IP_BLOCKER.default_rule="whitelisting" ``` for whitelisting as the mode of operation - any IP addresses you then add will be allowed through. 


I believe the README provides all the required information. You can reply to this if there's further doubts you need clarified.
